version: '3.5'
services:
  fridge:
    container_name: fridge
    image: fridge
    restart: unless-stopped
    environment:
      - FRIDGE_PROFILE=server
      - MONGO_URI=mongodb://root:1ua736qxyrw8tsy59r5f@mongo:27017/fridge?authSource=admin
    volumes:
      - /data/fridge:/data/fridge

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: unless-stopped
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1ua736qxyrw8tsy59r5f
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"
